apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: eap-operator
  annotations:
    description: Template to deploy a EAP operator on OCP 4 - obviously based on Alvaro's work
    tags: eap,operator
    iconClass: icon-eap
    openshift.io/provider-display-name: Red Hat, Inc.
    openshift.io/support-url: https://access.redhat.com
objects:
- apiVersion: project.openshift.io/v1
  kind: Project
  metadata:
    name: ${OPERATOR_NAMESPACE}
    annotations:
      openshift.io/description: "This project contains all the resources related to the operator of EAP"
      openshift.io/display-name: "EAP - Operator"
- apiVersion: project.openshift.io/v1
  kind: Project
  metadata:
    name: ${CLUSTER_NAMESPACE}
    annotations:
      openshift.io/description: "This project contains all the clusters deployed of EAP"
      openshift.io/display-name: "EAP"
- apiVersion: operators.coreos.com/v1
  kind: OperatorGroup
  metadata:
    name: eap
    namespace: ${OPERATOR_NAMESPACE}
  spec:
    targetNamespaces:
      - ${CLUSTER_NAMESPACE}
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    name: eap-operator
    namespace: ${OPERATOR_NAMESPACE}
  spec:
    channel: stable
    installPlanApproval: Automatic
    name: eap
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: eap-operator.v2.3.2
parameters:
- name: OPERATOR_NAMESPACE
  description: "The project where the operator will be installed."
  required: false
  value: "eap-operator"
- name: CLUSTER_NAMESPACE
  description: "The project where the EAP cluster will be installed."
  required: false
  value: "eap"
